### ISSUE TITLE
Minitest/AssertMatch return error code

### ISSUE THREAD

**Issue by sylvain-msl** [rubocop/rubocop-minitest#183]
When bumping rubocop-minitest from 0.21.1 to 0.22.0 it threw:

> An error occurred while Minitest/AssertMatch cop was inspecting <file_path>

whether there is or not an offense.

--------

## Expected behavior

Rubocop Minitest can run without returning an error code

## Actual behavior

It return a non-zero exit code with the following output:

> Scanning <file_path.rb>
> An error occurred while Minitest/AssertMatch cop was inspecting <file_path.rb>:176:4.
> undefined method `regexp_type?' for nil:NilClass
> /home/me/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-minitest-0.22.0/lib/rubocop/cop/mixin/minitest_cop_rule.rb:88:in > `new_arguments'
> /home/me/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-minitest-0.22.0/lib/rubocop/cop/mixin/minitest_cop_rule.rb:70:in  `offense_message'
> /home/me/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-minitest-0.22.0/lib/rubocop/cop/mixin/minitest_cop_rule.rb:41:in  `on_send'

...

> 1 file inspected, no offenses detected
>
> 2 errors occurred:
> An error occurred while Minitest/AssertMatch cop was inspecting <file_path.rb>:176:4.
> An error occurred while Minitest/AssertMatch cop was inspecting <file_path.rb>:176:4.

> Errors are usually caused by RuboCop bugs.
> Please, report your problems to RuboCop's issue tracker.
> Mention the following information in the issue report:
> 1.36.0 (using Parser 3.1.2.1, rubocop-ast 1.21.0, running on ruby 3.1.2) [x86_64-linux]

## Steps to reproduce the problem

in a test add 

```ruby
assert <something>.exact_match
assert <something>.match
```

run `bundle exec rubocop --autocorrect-all <file_path.rb>`

## RuboCop version

```
╰─ bundle exec rubocop -V                                                                                                                                                                                                      
1.36.0 (using Parser 3.1.2.1, rubocop-ast 1.21.0, running on ruby 3.1.2) [x86_64-linux]
  - rubocop-doctolib 0.1.0
  - rubocop-minitest 0.22.0
  - rubocop-performance 1.15.0
  - rubocop-rails 2.15.2
  - rubocop-rake 0.6.0
```
